### PR TITLE
Rework the landing page to reflect diataxis principles

### PR DESCRIPTION
**Pull request by willingc**
This PR is focused on the end user of the documentation. It edits the landing page to more closely reflect the diataxis structure of the documentation. The intent of the PR is to improve the experience of readers and help guide them to information that will be most valuable for their use case.

### CODE REVIEW

**Comment by henryiii** [comment]
I like the idea, though I should add the warning (here, not in the landing page / PR) that some of the pages in guides are extremely (5 or 10+ years) out of date. I think seriously rewriting them, cutting as needed, would really improve the user experience on the site. (Compare to the guides on https://learn.scientific-python.org/development/guides for an example of something more up to date.)

Once that is done, then linking a few of the most useful guide pages, similar to the tutorial section, might be in order.

**Comment by BrenBarn** [comment]
@henryiii What is the relative utility of having a guide that is 10 years out of date vs. just removing it entirely?  Does it vary from one guide to another?  Or perhaps there could be some kind of "legacy" subsection where out-of-date guides are clearly separated from the rest?  I understand that actually updating the guides would require a lot of work, but if we at least know which ones are the most egregiously outdated, then maybe we can segregate them under a sub-index of some sort, so that a casual user visiting the page will know they're different from the more up-to-date parts.

**Comment by willingc** [comment]
@henryiii This PR is only to make an incremental improvement as a stopgap to help new people landing on the page. There definitely needs to be a longer sustained effort to address out of date pages. I'm happy to help iteratively on some of those in separate PRs.

**Comment by willingc** [comment]
We may wish to create an epilog or prolog in a separate PR to notify readers that sections may be out of date.

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
(did a release via the web UI, to ensure that the merge is clean)

**Pull request merged**
