### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by AlexTereshenkov**
Fixing a typo in the documentation

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]

**Review by henryiii — APPROVED** [review]
I appprove. ;)

**Comment by AlexTereshenkov** [comment]
> I appprove. ;)

Thank you! Feel free to merge :)

**Comment by henryiii** [comment]
I don't have merge rights here, sorry. But I expect someone will get to it soon! Hopefully you enjoyed the careful spelling in my comment. ;)

**Comment by henryiii** [comment]
Fyi, a green check mark when approving in GitHub means the approver has merge rights.

**Comment by AlexTereshenkov** [comment]
> I don't have merge rights here, sorry. But I expect someone will get to it soon! Hopefully you enjoyed the careful spelling in my comment. ;)

No problem! No rush with that - was consulting the docs recently and saw that thing; couldn't resist the urge to tidy it up :) thanks a lot guys on the docs work, the docs are extremely useful and super well structured, pleasure to work with!

**Review by bfox85 — APPROVED** [review]

**Review by di — APPROVED** [review]

**Pull request merged**
