### PR TITLE
Consistent changelogs for all specs

### LINKED ISSUE #1203: Add changelogs to all standards
It would be good to add a “History” section to all [PyPA specifications](https://packaging.python.org/en/latest/specifications/), [like the one in `direct-url`](https://packaging.python.org/en/latest/specifications/direct-url/#history).
Even with a single entry, the section is useful -- to set expectations for future updates.
Please add dates if the spec isn't versioned in another way.
See [discussion on Discourse](https://discuss.python.org/t/1659/28).

### PR DESCRIPTION
**Pull request by jeanas**
Fixes #1203

----
📚 Documentation preview 📚: https://python-packaging-user-guide--1464.org.readthedocs.build/en/1464/

### CODE REVIEW

**Comment by jeanas** [comment]
@encukou

**Review by webknjaz — APPROVED** [review]
I think this looks good, but would like to get more opinions.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
I'm good with the change!

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
Clicking auto-merge eagerly on this since, IIUC, it'll wait on the outstanding reviews.

If it does not, apologies and please do review this post-merge and I (or @jeanas, should they be willing 😅) will address that feedback.

**Comment by jeanas** [comment]
> Clicking auto-merge eagerly on this since, IIUC, it'll wait on the outstanding reviews.

Well, you just merged the change, since it had already been approved by @webknjaz, @brettcannon and yourself (I don't understand GitHub well enough to tell what exactly the condition for auto-merge to trigger is). :slightly_smiling_face:

> If it does not, apologies and please do review this post-merge and I (or @jeanas, should they be willing 😅) will address that feedback.

Sure, I will happily apply further feedback (although I may have less time temporarily due to Christmas etc.).

**Comment by pradyunsg** [comment]
> I don't understand GitHub well enough to tell what exactly the condition for auto-merge to trigger is

Evidently, same. 😅

**Comment by webknjaz** [comment]
The branch protection requires just one approval from anyone. So it goes through unless blocked. No biggie, though.

**Pull request merged**
