### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by TarunavBA**
We should make a `contributing.md`  to make this project an OSS project! 😄

### CODE REVIEW

**Comment by TarunavBA** [comment]
Anyone pls approve this contribution from @TarunavBA

**Comment by bhrutledge** [comment]
This project already has a contributing guide at https://github.com/pypa/packaging.python.org/blob/main/source/contribute.rst, visible at https://packaging.python.org/contribute/.

I would consider a PR that would add a `CONTRIBUTING.md` with a link to that page.

**Comment by webknjaz** [comment]
It should probably be added to the `.github` repo instead.

**Comment by TarunavBA** [comment]
Hey I have made a new PR please check it out and let me contribute to this
repo.

~ 🤖

**Comment by webknjaz** [comment]
> let me contribute to this repo.

In order to contribute, first you need to figure out what contributions would be useful and understand the purpose of the project.

**Pull request closed without merging**
