### PR TITLE
Document hosted/managed package indexes

### PR DESCRIPTION
**Pull request by EpicWink**
Add a list of hosted and managed package index services to indicate to new users they don't have to build their own solution (as currently that's all the guide suggests at the moment, apart from devpi). Also include documentation links

### CODE REVIEW

**Comment by chrysle** [comment]
Generally unsure if we should include non-free services in the guide.. Maybe someone else can say something about that?

**Comment by sinoroc** [comment]
Preview: https://python-packaging-user-guide--1367.org.readthedocs.build/en/1367/guides/hosting-your-own-index/#hosted-and-managed-solutions

**Comment by willingc** [comment]
Hmm...I don't think that we have ever recommended a commercial solution in other docs for Python. I think the decision is a governance one and what the PSF and PyPA policy is.

That said I think folks would find the info valuable hosted as a personal doc on RTD about commercial hosting options.

**Comment by EpicWink** [comment]
Something like https://epicwink.github.io/python-index-services/?

**Comment by jeanas** [comment]
It sounds like there is consensus on not listing proprietary and paid services, so I'm going to close this PR, but please feel free to reopen if I've misunderstood.

**Pull request closed without merging**
