### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by meowmeowmeowcat**

### CODE REVIEW

**Review by webknjaz — COMMENTED** [review]
Please use intersphinx references instead of the hardcoded URLs to avoid such problems in the future.

**Comment by meowmeowmeowcat** [comment]
FIxed!

**Review by webknjaz — APPROVED** [review]

**Comment by meowmeowmeowcat** [comment]
@webknjaz Should I open a new PR for using intersphinx references instead of the hardcoded URLs in the docs?

**Comment by webknjaz** [comment]
If you feel like doing a repo-global crusade — go for it!

**Pull request merged**
