### PR TITLE
docs: add notice about PEP 715

### PR DESCRIPTION
**Pull request by miketheman**
Refs: https://peps.python.org/pep-0715/

### CODE REVIEW

**Comment by miketheman** [comment]
I don't know if the linkcheck issue is mine to solve - looks like an unrelated GitHub anchor resolution?

**Review by sinoroc — APPROVED** [review]

**Review by di — APPROVED** [review]

**Review by woodruffw — APPROVED** [review]

**Comment by di** [comment]
Going to go ahead and merge this because it's August 1 and https://github.com/pypi/warehouse/pull/14118 has been merged.

**Review by theacodes — APPROVED** [review]

**Comment by theacodes** [comment]
I gotchu, @di. I'd add you to the team but I'm not powerful enough.

**Comment by theacodes** [comment]
Actually it looks like I can only enable auto-merge when all checks pass, so that linkcheck check needs to pass first.

**Comment by di** [comment]
@theacodes Thanks! I think https://github.com/pypa/packaging.python.org/pull/1279 should do that.

**Pull request merged**
