### PR TITLE
Use environment variables instead of contexts

### LINKED ISSUE #1748: zizmor reveals "github.ref_name may expand into attacker-controllable code", should something else be used?
### Issue Description

If I run [zizmor](https://github.com/woodruffw/zizmor) against the workflow in https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#the-whole-ci-cd-workflow, then it finds

```
89 |         # sigstore-produced signatures and certificates.
90 |         run: >-
   |  _______^
91 | |         gh release upload
92 | |         '${{ github.ref_name }}' dist/**
93 | |         --repo '${{ github.repository }}'
   | |__________________________________________^ github.ref_name may expand into attacker-controllable code
```

Should something else be recommended instead?

### Code of Conduct

- [X] I am aware that participants in this repository must follow the PSF Code of Conduct.

### PR DESCRIPTION
**Pull request by tomkins**
Closes #1748

Updates the "Signing the distribution packages" section to use environment variables rather than GitHub Actions context variables. No additional setting of environment variables are needed - these are all set/available already.

I've got a repo where we're using trusted publishing, although it's a slight variation on this, but hopefully it's an example that the environment variables work just fine:

https://github.com/developersociety/django-findreplace/blob/7fcf87397590b984dacaca58719f2d8b737d4f77/.github/workflows/publish.yml#L81
https://github.com/developersociety/django-findreplace/actions/runs/12457101550

----
📚 Documentation preview 📚: https://python-packaging-user-guide--1765.org.readthedocs.build/en/1765/

### CODE REVIEW

**Comment by tomkins** [comment]
I've also added a `persist-credentials: false` for checkout, which is another potential zizmor found issue.

This might be overkill for fixing, as in theory the directory should never be added into a package. However, if for some bizarre reason a mistake is made - it would be good to help prevent it.

After this, zizmor is happy with the file:

```
$ zizmor --gh-token "$(gh auth token)" ./source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
2024-12-22T20:51:21.772745Z  INFO audit: zizmor: 🌈 completed /Users/tomkins/Development/packaging.python.org/source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
No findings to report. Good job! (9 suppressed)
```

**Review by ncoghlan — APPROVED** [review]
LGTM! Thanks.

I added a link to the relevant zizmor issue explanation to the original bug report.

**Comment by ncoghlan** [comment]
PyPI still has its webscraping protections turned on (https://github.com/pypa/packaging.python.org/issues/1744), so I expect the merge quest to fail (alas)

**Comment by ncoghlan** [comment]
Pending checks seem to be in a weird state. Closing/reopening to try to kick them.

**Comment by ncoghlan** [comment]
Huh, looks like it may have been a bug in the new check review widget (the workflows needed approval to run, but the review widget didn't tell me that, I had to go look at the Actions UI)

**Comment by webknjaz** [comment]
@ncoghlan I've working around that by manually going to the checks/actions tab and clicking the button in the workflow..

**Pull request merged**
