### PR TITLE
Bump linters and add ruff for consistent formatting across the codebase

### PR DESCRIPTION
**Pull request by pradyunsg**
I'd like to avoid having any discussions about code style/formatting in this codebase, so let's adopt a tool that'll handle it for us.

### CODE REVIEW

**Review by webknjaz — COMMENTED** [review]
Consistency doesn't necessarily mean changes. Can we leave the quotes alone?

**Comment by pradyunsg** [comment]
> Can we leave the quotes alone?

It's the defaults of the tool, which I'd prefer to leave as-is. Do you feel strongly about this?

**Comment by webknjaz** [comment]
Kinda

**Comment by pradyunsg** [comment]
Given the non-committal answer, I'm inclined to suggest that we move forward with this as-is. This is not a Python codebase with thousands of lines of complex logic -- there's 2 configuration files written in Python with at most if statements.

**Review by webknjaz — APPROVED** [review]

**Comment by pradyunsg** [comment]
(I should add the reformatting commit to blame ignore)

**Pull request merged**
