### PR TITLE
Add reference to PEP 610

### PR DESCRIPTION
**Pull request by sbidoul**
As proposed by @ncoghlan in https://discuss.python.org/t/draft-pep-recording-the-origin-of-distributions-installed-from-direct-url-references/1535/41?u=sbidoul

### CODE REVIEW

**Comment by sbidoul** [comment]
@ncoghlan ah ok, I was not sure since, since many other entries in the specifications page are merely pointers to the related PEP.

At which point should we copy the spec here? I assume the PEP should move out of Draft state first?

**Comment by ncoghlan** [comment]
@sbidoul We used to use the PEPs as the primary reference, so we've just been opportunistically migrating them as they get updated for other reasons (e.g. PEP 566 was really about defining metadata 2.1, but it *also* migrated to using packaging.python.org as the main reference page for the core metadata spec).

But yeah, for the initial draft, it makes sense to get it to Accepted before duplicating all the details over here. The key thing to add to the PEP is the long term URL you plan to use, and I think your suggestion of https://packaging.python.org/specifications/direct-url is a clear and sensible choice.

**Comment by sbidoul** [comment]
> The key thing to add to the PEP is the long term URL you plan to use, and I think your suggestion of https://packaging.python.org/specifications/direct-url is a clear and sensible choice

@ncoghlan done in https://github.com/python/peps/pull/1283

**Comment by sbidoul** [comment]
I updated this PR with the full specification extracted from PEP 610.

cc/ @ncoghlan @pradyunsg

**Review by pradyunsg — APPROVED** [review]
I've skimmed this to check the major bits, and not gone line by line. OTOH, I'm pretty sure that @sbidoul isn't gonna sneakily change a detail from their own PEP. 🙃

**Comment by sbidoul** [comment]
@pradyunsg indeed, I only tweaked rst formatting (title underlines and roles), and adjusted the first few lines so it reads better.

This reminds me, though, that I had [said](https://discuss.python.org/t/draft-pep-recording-the-origin-of-distributions-installed-from-direct-url-references/1535/59?u=sbidoul) that I'd leave out the part about `resolved_revision` and `resolved_revision_type` in the spec, because it is currently not implemented anywhere. So I've just added a commit removing that.

**Review by ncoghlan — APPROVED** [review]

**Pull request merged**
