### PR TITLE
Remove the sample project MANIFEST.in reference

### PR DESCRIPTION
**Pull request by DiddiLeija**
If pypa/sampleproject#155 gets merged, the link may get broken, and also may cause a confussion. So, this PR removes the only reference to that file, and also explained why.

### CODE REVIEW

**Comment by DiddiLeija** [comment]
Ok, the tests failed:

```
/home/runner/work/packaging.python.org/packaging.python.org/source/guides/installing-scientific-packages.rst:16: WARNING: unknown document: scipy:stackspec
/home/runner/work/packaging.python.org/packaging.python.org/source/guides/installing-scientific-packages.rst:92: WARNING: undefined label: scipy:mac
/home/runner/work/packaging.python.org/packaging.python.org/source/guides/installing-scientific-packages.rst:101: WARNING: unknown document: scipy:install
```

However, this seems to be external to this PR, right?

**Comment by DiddiLeija** [comment]
> However, this seems to be external to this PR, right?

Oh, I see that #1006 wants to fix this issue.

**Comment by DiddiLeija** [comment]
Excluding the above issue, do I have to do something else?

**Comment by webknjaz** [comment]
@DiddiLeija wait for the reviews, I guess.

**Review by webknjaz — APPROVED** [review]

**Comment by DiddiLeija** [comment]
Thanks @webknjaz!

**Pull request merged**
