### PR TITLE
Update support link

### PR DESCRIPTION
**Pull request by bhrutledge**

### CODE REVIEW

**Comment by pradyunsg** [comment]
I'm not sure that we want to direct support requests to Discourse at this point. Something like pypa/packaging-problems is much better suited for support requests nowadays.

**Comment by webknjaz** [comment]
Honestly, I think that having discussions enabled in this repo could serve the same purpose.

**Comment by pfmoore** [comment]
I'd definitely prefer *not* to use the packaging Discourse for user support. If we need a "user help" forum it should either be a separate Discourse category, or something like discussions on this repo.

**Review by pfmoore — CHANGES_REQUESTED** [review]
See my comments - I should probably have made them a review. We should not use the existing Packaging category on Discourse for "user help" types of query.

**Comment by pradyunsg** [comment]
> Honestly, I think that having discussions enabled in this repo could serve the same purpose.

We already have a place where we have users come to ask for help - the issue tracker on packagong-problems. I don't think adding another channel for users to ask for helps, helps anyone here. We'd be stretching our already-limited volunteer energy across more spaces making it even less likely that someone responds.

**Comment by webknjaz** [comment]
Not additionally but rather instead.

**Comment by bhrutledge** [comment]
Thanks, folks. I've linked to https://github.com/pypa/packaging-problems.

**Comment by pradyunsg** [comment]
> Not additionally but rather instead.

Ah, okay. We could, but that's still a discussion to be had with more people than just us. :)

**Review by pradyunsg — APPROVED** [review]

**Review by pfmoore — APPROVED** [review]

**Pull request merged**
