### PR TITLE
When publishing to Pipy,  your username should be __token__

### PR DESCRIPTION
**Pull request by danfunk**
I found I had to add this for the tutorial to work properly.  Otherwise flawless, thank you!

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
Thanks for this but I prefer only specifying the required fields. The reason is that the action defaults to `__token__` and it was designed to only need an explicit username when the end-users actually need to use passwords and not tokens (for example, when they want to upload to something like [devpi].

Are there any reasons not to keep the example simple as it is now?

[devpi]: https://devpi.net/docs/devpi/devpi/6.0/+d/

**Comment by webknjaz** [comment]
> for the tutorial to work properly

If you've faced problems, I don't believe that they were caused by an implicit [`__token__`](https://github.com/pypa/gh-action-pypi-publish/blob/bea5cda/action.yml#L8). But my guess would be that you may have copied the token into the secrets incorrectly (with trailing/leading whitespace or something else missing) — this happens sometimes and is a user error.

**Comment by danfunk** [comment]
I agree that if the default value is __token__, it would better not to set it.
I went back, and everything worked fine this time when I did not set the user name.   Sorry for the trouble.

**Comment by webknjaz** [comment]
No problems :) Voicing your concerns is no trouble at all!

If you want to contribute some tutorial improvements, it may be a good idea to update `@master` to be `@release/v1`, plus maybe bump other action versions, and drop `--sdist`+`--wheel` args from the build command to get the latest improvements it has related to them (or even drop all the args for simplicity).

**Review by Ririe91 — COMMENTED** [review]
48808377

**Pull request closed without merging**
